### PR TITLE
Gamify: JavaScript Capstone | Final Merge to Master

### PR DESCRIPTION
**Pull request by michael-duke**
## Capstone II final milestone:
In this project @aceDavon and @michael-duke have:

- Used JavaScript to make websites dynamic and build basic single page apps.
- Used ES6 syntax, and ES6 modules.
- Used `callbacks` and `promises`.
- Used webpack to setup our bundles, and Jest for testing 
- Applied JavaScript best practices and language style guides in code.
- Used Arrange Act, and Assert pattern for unit tests. (also know as AAA)
- Written units tests for a JavaScript app.
- Followed proper Gitflow.
- Solved simple `git` conflicts.
- Consumed data from an `API`.
- Used `API` documentation.
- Understood and used `JSON`.
- Made JavaScript code asynchronous, with `async` and `await`.
- Performed a code review for a team member.
- Implemented interfaces for the homepage, trailers page and contact page.
- Implemented interfaces for comment popup
- Here is  a [link](https://drive.google.com/file/d/15B_4pZ8LjQf_niIBs0kPBHx7DK_IGTpZ/view?usp=sharing) to the presentation :smile: 🚀  and final [website](https://michael-duke.github.io/Capstone-II/) 🎮

### CODE REVIEW

**Review by omar-muhamad — APPROVED** [review]
# Approved ✔
### Hi @michael-duke and @aceDavon,

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

thumbs-up-agree


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by michael-duke** [comment]
Thank you @Omar-Muhamad, it was a pleasure :smile: :rocket: Happy Coding

**Comment by omar-muhamad** [comment]
> Thank you @Omar-Muhamad, it was a pleasure :smile: :rocket: Happy Coding

You're welcome @michael-duke,
Your project looks awesome, your code is clean, and you fulfilled all requirements.
Have a great weekend ☺️.

**Comment by michael-duke** [comment]
Our combined skills paid off, you have a great weekend too @Omar-Muhamad :smile:

**Comment by Omar-Muhamad** [comment]
I know I see the commits history and I meant both of you in last comment.

**Pull request merged**
